Public Class Form1

    Private Sub RadioButton6_CheckedChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub

    Private Sub Form1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

    End Sub

    Private Sub LinkLabelteam_LinkClicked(ByVal sender As System.Object, ByVal e As System.Windows.Forms.LinkLabelLinkClickedEventArgs)

    End Sub

    Private Sub ComboBox1_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnchoose.Click
        If ComboBox1.Text = "" Then
            MsgBox("«œŒ· —ﬁ„ «·√”»Ê⁄", MsgBoxStyle.Exclamation)
        End If
        If ComboBox1.Text = "«Œ — —ﬁ„ «·√”»Ê⁄" Then
            MsgBox("«œŒ· —ﬁ„ «·√”»Ê⁄", MsgBoxStyle.Exclamation)
        End If

        If ComboBox1.Text = "1" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "≈ Õ«œ «·‘—ÿ…"
            lbl1.Text = "0"
            lbl2.Text = "0"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = True
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "2" Then
            lblt1.Text = "ÿ·«∆⁄ «·ÃÌ‘"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "0"
            lbl2.Text = "1"
            lbl1b.Text = "Õ”«„ ⁄«‘Ê—"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = True
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "3" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·„’—Ï «·»Ê—”⁄ÌœÏ"
            lbl1.Text = "1"
            lbl2.Text = "1"
            lbl1a.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = True
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "4" Then
            lblt1.Text = "«·ÃÊ‰…"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "1"
            lbl1b.Text = "‘Â«» «·œÌ‰ √Õ„œ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ÃÊ‰…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = True
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "5" Then
            lblt1.Text = "«·≈ Õ«œ «·”ﬂ‰œ—Ï"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "2"
            lbl2.Text = "2"
            lbl1b.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl2b.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·√”ﬂ‰œ—Ì…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = True
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "6" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "Ê«œÏ œÃ·…"
            lbl1.Text = "1"
            lbl2.Text = "0"
            lbl1a.Text = "Õ”«„ €«·Ï"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = True
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "7" Then
            lblt1.Text = "«·≈‰ «Ã «·Õ—»Ï"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "2"
            lbl1b.Text = "„Õ„œ ›÷·"
            lbl2b.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = True
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "8" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "Õ—” «·ÕœÊœ"
            lbl1.Text = "2"
            lbl2.Text = "1"
            lbl1a.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl2a.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = True
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "9" Then
            lblt1.Text = "» —ÊÃÌ "
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "0"
            lbl2.Text = "1"
            lbl1b.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·”ÊÌ”"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = True
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "10" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "≈‰»Ï"
            lbl1.Text = "3"
            lbl2.Text = "2"
            lbl1a.Text = "‘—Ì› ⁄»œ «·›÷Ì·"
            lbl2a.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl3a.Text = "„Õ„œ »—ﬂ« "
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = True
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "11" Then
            lblt1.Text = "«·≈”„«⁄Ì·Ï"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "3"
            lbl2.Text = "1"
            lbl1b.Text = "√Õ„œ › ÕÏ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·≈”„«⁄Ì·Ì…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = True
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "12" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·“„«·ﬂ"
            lbl1.Text = "0"
            lbl2.Text = "0"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = True
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "13" Then
            lblt1.Text = "”„ÊÕ…"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "1"
            lbl1b.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·√”ﬂ‰œ—Ì…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = True
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "14" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·„ﬁ«Ê·Ê‰ «·⁄—»"
            lbl1.Text = "1"
            lbl2.Text = "1"
            lbl1a.Text = "√Õ„œ ‘ﬂ—Ï"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = True
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "15" Then
            lblt1.Text = "„’— ··„ﬁ«’…"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "1"
            lbl1b.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = True
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "16" Then
            lblt1.Text = "≈ Õ«œ «·‘—ÿ…"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "2"
            lbl1b.Text = "„Õ„œ ‘ÊﬁÏ"
            lbl2b.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = True
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "17" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "ÿ·«∆⁄ «·ÃÌ‘"
            lbl1.Text = "1"
            lbl2.Text = "0"
            lbl1a.Text = "„Õ„œ ›÷·"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = True
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "18" Then
            lblt1.Text = "«·„’—Ï «·»Ê—”⁄ÌœÏ"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "0"
            lbl2.Text = "0"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "»Ê—”⁄Ìœ"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = True
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "19" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·ÃÊ‰…"
            lbl1.Text = "1"
            lbl2.Text = "0"
            lbl1a.Text = "√”«„Â Õ”‰Ï"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = True
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "20" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·≈ Õ«œ «·”ﬂ‰œ—Ï"
            lbl1.Text = "1"
            lbl2.Text = "0"
            lbl1a.Text = "Ê«∆· Ã„⁄…"
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = True
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "21" Then
            lblt1.Text = "Ê«œÏ œÃ·…"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "2"
            lbl1b.Text = "√Õ„œ ‰»Ì· „«‰ÃÂ"
            lbl2b.Text = "œÊ„Ì‰Ìﬂ œ«”Ì·›«"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = True
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "22" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·≈‰ «Ã «·Õ—»Ï"
            lbl1.Text = "2"
            lbl2.Text = "2"
            lbl1a.Text = "√Õ„œ › ÕÏ"
            lbl2a.Text = "⁄»œ «·Õ„Ìœ ‘»«‰…"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = True
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "23" Then
            lblt1.Text = "Õ—” «·ÕœÊœ"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "0"
            lbl2.Text = "3"
            lbl1b.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl2b.Text = "√Õ„œ › ÕÏ"
            lbl3b.Text = "√Õ„œ Õ”‰"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·√”ﬂ‰œ—Ì…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = True
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "24" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "» —ÊÃÌ "
            lbl1.Text = "2"
            lbl2.Text = "0"
            lbl1a.Text = "√Õ„œ › ÕÏ"
            lbl2a.Text = "”Ìœ „⁄Ê÷"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = True
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "25" Then
            lblt1.Text = "≈‰»Ï"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "2"
            lbl1b.Text = "œÊ„Ì‰Ìﬂ œ«”Ì·›«"
            lbl2b.Text = "⁄„«œ „ ⁄»"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = True
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "26" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "«·≈”„«⁄Ì·Ï"
            lbl1.Text = "2"
            lbl2.Text = "1"
            lbl1a.Text = "„Õ„œ »—ﬂ« "
            lbl2a.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = True
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "27" Then
            lblt1.Text = "«·“„«·ﬂ"
            lblt2.Text = "««·√Â·Ï"
            lbl1.Text = "2"
            lbl2.Text = "2"
            lbl1b.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl2b.Text = "œÊ„Ì‰Ìﬂ œ«”Ì·›«"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = True
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "28" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "”„ÊÕ…"
            lbl1.Text = "2"
            lbl2.Text = "2"
            lbl1a.Text = "√”«„Â Õ”‰Ï"
            lbl2a.Text = "√Õ„œ «·”Ìœ"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = True
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "29" Then
            lblt1.Text = "«·„ﬁ«Ê·Ê‰ «·⁄—»"
            lblt2.Text = "«·√Â·Ï"
            lbl1.Text = "1"
            lbl2.Text = "5"
            lbl1b.Text = "Ê«∆· Ã„⁄…"
            lbl2b.Text = "„Õ„œ »—ﬂ« "
            lbl3b.Text = "‘—Ì› ⁄»œ «·›÷Ì·"
            lbl4b.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl5b.Text = "Õ”«„ €«·Ï"
            lbl1a.Text = ""
            lbl2a.Text = ""
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = False
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = True
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = True
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = False
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
        If ComboBox1.Text = "30" Then
            lblt1.Text = "«·√Â·Ï"
            lblt2.Text = "„’— «·„ﬁ«’…"
            lbl1.Text = "2"
            lbl2.Text = "2"
            lbl1a.Text = "√Õ„œ Õ”‰"
            lbl2a.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl3a.Text = ""
            lbl4a.Text = ""
            lbl5a.Text = ""
            lbl1b.Text = ""
            lbl2b.Text = ""
            lbl3b.Text = ""
            lbl4b.Text = ""
            lbl5b.Text = ""
            lbls.Text = "«·ﬁ«Â—…"
            lble1a.Visible = True
            lble2a.Visible = False
            lble3a.Visible = False
            lble4a.Visible = False
            lble5a.Visible = False
            lble6a.Visible = False
            lble9a.Visible = False
            lble10a.Visible = False
            lble12a.Visible = False
            lble13a.Visible = False
            lble14a.Visible = False
            lble15a.Visible = False
            lble16a.Visible = False
            lble17a.Visible = False
            lble18a.Visible = False
            lble19a.Visible = False
            lble1b.Visible = False
            lble2b.Visible = False
            lble3b.Visible = False
            lble4b.Visible = False
            lble5b.Visible = False
            lble6b.Visible = False
            lble9b.Visible = False
            lble10b.Visible = False
            lble12b.Visible = False
            lble13b.Visible = False
            lble14b.Visible = True
            lble15b.Visible = False
            lble16b.Visible = False
            lble17b.Visible = False
            lble18b.Visible = False
            lble19b.Visible = False
            btn11.Visible = False
            btn22.Visible = False
            btn33.Visible = False
            btn44.Visible = False
        End If
    End Sub

    Private Sub btns_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btns.Click
        lbl1a.Text = ""
        lbl2a.Text = ""
        lbl3a.Text = ""
        lbl4a.Text = ""
        lbl5a.Text = ""
        lbl1b.Text = ""
        lbl2b.Text = ""
        lbl3b.Text = ""
        lbl4b.Text = ""
        lbl5b.Text = ""
        lbl1.Text = ""
        lbl2.Text = ""
        lblt1.Text = "«·«Õ’«¡"
        lblt2.Text = "«·⁄œœ"
        lble1a.Visible = True
        lble2a.Visible = False
        lble3a.Visible = False
        lble4a.Visible = False
        lble5a.Visible = False
        lble6a.Visible = False
        lble9a.Visible = False
        lble10a.Visible = False
        lble12a.Visible = False
        lble13a.Visible = False
        lble14a.Visible = False
        lble15a.Visible = False
        lble16a.Visible = False
        lble17a.Visible = False
        lble18a.Visible = False
        lble19a.Visible = False
        lble1b.Visible = True
        lble2b.Visible = False
        lble3b.Visible = False
        lble4b.Visible = False
        lble5b.Visible = False
        lble6b.Visible = False
        lble9b.Visible = False
        lble10b.Visible = False
        lble12b.Visible = False
        lble13b.Visible = False
        lble14b.Visible = False
        lble15b.Visible = False
        lble16b.Visible = False
        lble17b.Visible = False
        lble18b.Visible = False
        lble19b.Visible = False
        ComboBox1.Text = ""
        btn11.Visible = True
        btn22.Visible = True
        btn33.Visible = True
        btn44.Visible = True
        lbls.Text = "«Œ — —ﬁ„ «·’›Õ…"
    End Sub

    Private Sub Label13_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles lble2a.Click

    End Sub

    Private Sub btng_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btng.Click
        lblt1.Text = "«··«⁄»"
        lblt2.Text = "⁄œœ «·√Âœ«›"
        lbl1a.Text = ""
        lbl2a.Text = ""
        lbl3a.Text = ""
        lbl4a.Text = ""
        lbl5a.Text = ""
        lbl1b.Text = ""
        lbl2b.Text = ""
        lbl3b.Text = ""
        lbl4b.Text = ""
        lbl5b.Text = ""
        lble1a.Visible = True
        lble2a.Visible = False
        lble3a.Visible = False
        lble4a.Visible = False
        lble5a.Visible = False
        lble6a.Visible = False
        lble9a.Visible = False
        lble10a.Visible = False
        lble12a.Visible = False
        lble13a.Visible = False
        lble14a.Visible = False
        lble15a.Visible = False
        lble16a.Visible = False
        lble17a.Visible = False
        lble18a.Visible = False
        lble19a.Visible = False
        lble1b.Visible = True
        lble2b.Visible = False
        lble3b.Visible = False
        lble4b.Visible = False
        lble5b.Visible = False
        lble6b.Visible = False
        lble9b.Visible = False
        lble10b.Visible = False
        lble12b.Visible = False
        lble13b.Visible = False
        lble14b.Visible = False
        lble15b.Visible = False
        lble16b.Visible = False
        lble17b.Visible = False
        lble18b.Visible = False
        lble19b.Visible = False
        ComboBox1.Text = ""
        btn11.Visible = True
        btn22.Visible = True
        btn33.Visible = True
        btn44.Visible = True
        lbls.Text = "«Œ — —ﬁ„ «·’›Õ… "
    End Sub

    Private Sub btn11_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn11.Click
        If lblt1.Text = "«··«⁄»" Then
            lbl1a.Text = "„Õ„œ √»Ê  —ÌﬂÂ"
            lbl1b.Text = "8"
            lbl2a.Text = "„Õ„œ ‰«ÃÏ ÃœÊ"
            lbl2b.Text = "8"
            lbl3a.Text = "√Õ„œ › ÕÏ"
            lbl3b.Text = "4"
            lbl4a.Text = "œÊ„Ì‰Ìﬂ œ«”Ì·›«"
            lbl4b.Text = "3"
            lbl5a.Text = "„Õ„œ »—ﬂ« "
            lbl5b.Text = "3"
        End If
        If lblt1.Text = "«·«Õ’«¡" Then
            lbl1a.Text = "·⁄»"
            lbl1b.Text = "30"
            lbl2a.Text = "›Ê“"
            lbl2b.Text = "15"
            lbl3a.Text = " ⁄«œ·"
            lbl3b.Text = "14"
            lbl4a.Text = "Â“Ì„…"
            lbl4b.Text = "1"
            lbl5a.Text = "÷—»«  Ã“«¡"
            lbl5b.Text = "6"
        End If
    End Sub

    Private Sub btn22_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn22.Click

        If lblt1.Text = "«··«⁄»" Then
            lbl1a.Text = "„Õ„œ ›÷·"
            lbl1b.Text = "2"
            lbl2a.Text = "Õ”«„ €«·Ï"
            lbl2b.Text = "2"
            lbl3a.Text = "‘—Ì› ⁄»œ «·›÷Ì·"
            lbl3b.Text = "2"
            lbl4a.Text = "√”«„Â Õ”‰Ï"
            lbl4b.Text = "2"
            lbl5a.Text = "Ê«∆· Ã„⁄…"
            lbl5b.Text = "2"
        End If
        If lblt1.Text = "«·«Õ’«¡" Then
            lbl1a.Text = "·Â"
            lbl1b.Text = "47"
            lbl2a.Text = "⁄·ÌÂ"
            lbl2b.Text = "27"
            lbl3a.Text = "›«—ﬁ √Âœ«›"
            lbl3b.Text = "20"
            lbl4a.Text = "›«—ﬁ √Âœ«› œÊ— 1"
            lbl4b.Text = "4"
            lbl5a.Text = "›«—ﬁ √Âœ«› œÊ— 2"
            lbl5b.Text = "16"
        End If
    End Sub

    Private Sub btn33_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn33.Click
        If lblt1.Text = "«··«⁄»" Then
            lbl1a.Text = "√Õ„œ Õ”‰"
            lbl1b.Text = "2"
            lbl2a.Text = "Õ”«„ ⁄«‘Ê—"
            lbl2b.Text = "1"
            lbl3a.Text = "‘Â«» «·œÌ‰ √Õ„œ"
            lbl3b.Text = "1"
            lbl4a.Text = "√Õ„œ ‘ﬂ—Ï"
            lbl4b.Text = "1"
            lbl5a.Text = "⁄„«œ „ ⁄»"
            lbl5b.Text = "1"
        End If
        If lblt1.Text = "«·«Õ’«¡" Then
            lbl1a.Text = "›Ê“ œÊ— 1"
            lbl1b.Text = "5"
            lbl2a.Text = "›Ê“ œÊ— 2"
            lbl2b.Text = "10"
            lbl3a.Text = " ⁄«œ· œÊ— 1"
            lbl3b.Text = "9"
            lbl4a.Text = " ⁄«œ· œÊ— 2"
            lbl4b.Text = "5"
            lbl5a.Text = "Â“Ì„… œÊ— 1"
            lbl5b.Text = "1"
        End If
    End Sub

    Private Sub btn44_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btn44.Click
        If lblt1.Text = "«··«⁄»" Then
            lbl1a.Text = "„Õ„œ ‘ÊﬁÏ"
            lbl1b.Text = "1"
            lbl2a.Text = "⁄»œ «·Õ„Ìœ ‘»«‰…"
            lbl2b.Text = "1"
            lbl3a.Text = "”Ìœ „⁄Ê÷"
            lbl3b.Text = "1"
            lbl4a.Text = "√Õ„œ ‰»Ì· „«‰ÃÂ"
            lbl4b.Text = "1"
            lbl5a.Text = "√Õ„œ «·”Ìœ"
            lbl5b.Text = "1"
        End If
        If lblt1.Text = "«·«Õ’«¡" Then
            lbl1a.Text = "·Â œÊ— 1"
            lbl1b.Text = "18"
            lbl2a.Text = "·Â œÊ— 2"
            lbl2b.Text = "29"
            lbl3a.Text = "⁄·ÌÂ œÊ— 1"
            lbl3b.Text = "14"
            lbl4a.Text = "⁄·ÌÂ œÊ— 2"
            lbl4b.Text = "13"
            lbl5a.Text = "√”«»Ì⁄ «·ﬁ„…"
            lbl5b.Text = "6"
        End If
    End Sub
End Class
